### PR TITLE
Fixed support for gradients

### PR DESCRIPTION
**Pull request by ErikOnBike**
Hi Guillaume,

I've added some (hopefully ;-) better support for gradients. The original code was based solely on x, y, width and height parameters of the node (which are only present for rectangles). I have added code to calculate the bounding box for all shapes and texts. Texts are handled specially, but maybe the same approach could be used for all shapes.

I use SVG files generated by Visio a lot. These files often contain gradients because of default Visio templates. With the extra support these gradients seem to be supported. I have not been able to test it thoroughly because I have not gotten the regression tests to work. See the mail I sent you earlier.

Cheers,
Erik

### CODE REVIEW

**Comment by ErikOnBike** [comment]
Guillaume,

Used Travis to find out how to get regression tests to work. Had a regression and fixed it. All is working again.

There are still some things to fix though (*). Waiting for a reaction from you before continuing.

(*) Some issues with order in which elements are rendered (overlapping characters with gradients) for example. And one typical thing is a Cairo crash. Seems to be when trying to render a whitespace using "surface.context.text_path(letter)". Since it will not actually create any path, I made this line conditional. I'm working on Mac OS X (EC). On other platforms this might not be a problem.

Cheers,
Erik

**Comment by ErikOnBike** [comment]
Guillaume,

**I updated some more code wrt the gradients**
Gradients did not work correctly on some markers. Fixed an issue with the angle on 'mid'-markers while doing so.
Also had to update some code to prevent 'popping' attributes from nodes (which were still needed at a later time). The code now relies more on 'defaults' to be supplied by "node.get('myattr', defaultValue)" approach.

**I created some regression with my updates**
It looks like these are actually improvements. Some texts did not have 'stroke-width' set to 1:
- test/svg/coords-trans-10-f.svg
- test/svg/coords-trans-11-f.svg
- test/svg/coords-trans-12-f.svg
- test/svg/coords-trans-13-f.svg
- test/svg/coords-trans-14-f.svg
- test/svg/metadata-example-01-t.svg (zoom in onto paper on table! :-)

Fails moved from test/fail to test/svg:
- test/fail/pservers-grad-17-b.svg
- test/fail/pservers-grad-20-b.svg

It seems the following was put in test/svg accidentally, because it did not look good on my computer (one square instead of two). Seems to be fixed, but gives fail in regression test.
- test/svg/imp-path-01-f.svg

I'll be working some more on gradients, markers and patterns the coming days.

Cheers,
Erik

**Comment by liZe** [comment]
First of all: it's **cool**, thank you!!

1) The global logic is OK for me. The bounding box calculation is useful for gradients, but also for SVG images with no intrinsic size (we'll do this later).

2) The other changes made to the gradients (keeping the attributes, defaults, etc.) are great too.

3) The passing tests are really good news (and I love your last commit for that), and you even found some tests marked as passing when they were actually failing :+1:.

4) I'm not convinced by the code in the `bounding_box_*` functions. I'm not sure if it's a real problem or not, but some clues let me skeptical:
- they rely on `float` where they should probably rely on `size` (the worst point for me),
- they ignore the `transform` attribute of the nodes,
- they sometimes duplicate the "real" rendering loop (well, that's probably needed, but it makes me feel incomfortable).
My intuition tells me that we should rely on something like [recording surfaces](http://www.cairographics.org/manual/cairo-Recording-Surfaces.html) more than on manual calculations. But I may be wrong :).

5) The coding style is globally OK, but I like to keep the 79 characters limit ;).

I'll probably merge the branch during the week-end and play with it. Don't spend time fixing the style (I'll fix it myself, it's a kind of crazy personal mental illness :p).You can continue hacking on gradients on this PR, you can open new PRs for markers and patterns.

You can answer to my review, I'm curious to know what you think about it.

**Thank you** again!

**Comment by ErikOnBike** [comment]
Hi Guillaume,

Some remarks
1) Agree
2) Thanx
3) It would be nice if we could slowly remove all failed tests which are static (ie no animation or scripting). Maybe it is a good idea to keep a folder with issues we or others discover. Kind of like a backlog.
4) I'm hurt....no I'm just kidding ;-)
I'm using `float` and you are right that `size()` would be better. You mention also the duplication with the actual rendering loop. We might combine the two. For `text`-elements I'm already using the render loop (which was to difficult to do otherwise). Shall I move all calculations into the rendering loop? From a separation of concerns point of view I dislike this, but the duplication (and using `float` instead of `size()`) is probably worse. It was this 'approach' I mentioned in an earlier private mail.

Bounding boxes are explicitly calculated without transformation. This is according to the specification. See https://www.w3.org/TR/SVG/coords.html#ObjectBoundingBox

According to my interpretation of the specification the bounding boxes for the rendering of gradients (and patterns as well) are slightly 'relaxed' with respect to tightness for curved paths. It will use the control points as outer bounds instead of the real curves boundaries. If I look at the results of gradients applied to odd shaped curves (extreme control points), the results are almost pixel perfect with Safari (and very similar to Chrome/Firefox). The different browsers do have some small differences.

5) My bad. I'm not used to program in Python and have to learn some guidelines here. I'll take it into account. Feel free to restyle.

Same here: gradients on current PR other topics on separate branch/PR. Sometimes seemingly unrelated changes/fixes might end up on a topic. Like the marker orientation (`marker-mid`), which I stumbled upon trying to fix the gradient of these markers. Did not want to start a new branch for such a simple fix.  

I'm totally cool with the review, your mental illness (I would probably feel the same once I got the general style guide internalised) and I'm very happy with CairoSVG. You have done a great job!

Cheers,
Erik

**Comment by ErikOnBike** [comment]
Guillaume,

**Bounding box calculation inside render loop**
At the bottom is the code for rendering a circle in which I have added the bounding box 'calculation' (in most cases there is very little to calculate actually). The idea below is that the bounding box is stored inside the node. (I'm using the tuple notation for coordinates for now.)

For gradients and patterns this is probably enough, since these are drawn after the node is rendered. But for the general case, we could use the [recording surfaces](http://www.cairographics.org/manual/cairo-Recording-Surfaces.html) you mentioned. By storing the bounding box inside the node, no recalculation is required on multiple uses.

Does this seem like a sound approach? Anything I should be aware of?

**Some thoughts...**
Creating a 'recording surface' seems like an expensive operation (having to copy the current surface characteristics). One alternative to this approach would therefore be to have an extra argument `dryRun` (as used in `git`) for all rendering functions. This argument would get a default value `False`. When `True` is supplied, the actual rendering/drawing does not take place (but bounding box calculation will). I do not really like this approach but mention it for 'completeness'.
Of course we could also create classes for all shapes which better separate between these two responsibilities by having `get_bounding_box()` and `render()` methods on them. These two methods can share their knowledge about the actual shape.
Or should we stay with the current approach and keep bounding boxes and rendering as separate functions and accept some itchy feeling with respect to duplication?

Regardless of the approach chosen, I'll probably turn the `bounding_box` into a class instead of a set of separate functions.

Looking forward to reading/seeing your ideas.

Cheers,
Erik

Code example:
```
def circle(surface, node):
    """Draw a circle ``node`` on ``surface``."""
    r = size(surface, node.get('r'))
    if not r:
        return
    cx = size(surface, node.get('cx'), 'x')
    cy = size(surface, node.get('cy'), 'y')

    """Store bounding box info in ``node``."""
    set_bounding_box(node, (cx - r, cy - r), (cx + r, cy + r))

    """Perform actual draw."""
    surface.context.new_sub_path()
    surface.context.arc(cx, cy, r, 0, 2 * pi)

```

**Comment by liZe** [comment]
@ErikOnBike 

Thanks a lot for your thougths. I've merged the branch and fixed some points discussed here, including the use of `size` instead of `float`, and of course some style.

I'm quite happy with the current state of the master branch, it's a real improvement and I'm glad to know that it will help you with Visio templates. Thank you again for this pull request!

The idea of storing bounding boxes during the rendering process is probably the best solution, because (as you said) it often needs no big extra calculation. We can use a simple tuple for now, and maybe create a class after. I'm finally convinced that recording surfaces is probably a bad idea (but it could be useful when the size of the SVG is unknown, another possible improvement of your work, see [these related tests](https://github.com/Kozea/CairoSVG/tree/master/test/fail/viewbox)).

**Pull request merged**
