### PR TITLE
Update image.py

### PR DESCRIPTION
**Pull request by dsblank**
Add support for embedded data URIs.

### CODE REVIEW

**Comment by liZe** [comment]
Thank you for this pull request!

Data URLs are supposed to be already supported (and there's even a [test](https://github.com/Kozea/CairoSVG/blob/master/test/svg/conform-viewers-02-f.svg) for that)! Do you have an example that's not working without this PR?

**Comment by dsblank** [comment]
Maybe it was because we used `href` rather than `xlink:href`? In any event, none of our SVG images would work. In addition, I had to make a change to get non-blurry images:

https://github.com/Calysto/conx/commit/761db715fb5fb8bc87322e83eb3d5a18af06ba13#diff-a6a93b7b81780617bdc1c372a348a059

Here is part of one of our images:

```html
<svg id='XOR2' xmlns='http://www.w3.org/2000/svg' image-rendering="pixelated" width="400.0px" height="272.0px">
 <g >
  <svg viewBox="0 0 500 340" width="400.0px" height="272.0px">
    <defs>
        <marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto" markerUnits="strokeWidth">
          <path d="M0,0 L0,6 L9,3 z" fill="black" />
        </marker>
    </defs><rect x="115.66666666666666" y="24" width="102" height="52" style="fill:none;stroke:black;stroke-width:2"/><image id="picture-static-XOR2-679968_output1_8" class="picture-static-XOR2-679968_output1" x="116.66666666666666" y="25" height="50" width="100" preserveAspectRatio="none" href="data:image/gif;base64,R0lGODdhfAA+AIcAAE1N/319/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAfAA+AEAI/wAFCBxIsKDBgwgTKlzIsKHDhwUBSJxIsaLFixgzaqwoQECAjyBDihxJsqTJkyIFCADAsqXLlzBjypxJ86UAAQFy6tzJs6fPn0CD8hQgAIDRo0iTKl3KtKnTpAIEBJhKtarVq1izat1qVYAAAGDDih1LtqzZs2jHChAQoK3bt3Djyp1Lty5cAQIA6N3Lt6/fv4ADC+4rQECAw4gTK17MuLHjx4oFCABAubLly5gza97M+bIAAQFCix5NurTp06hTkxYgAIDr17Bjy55Nu7bt2AIEBNjNu7fv38CDCx/uW4AAAMiTK1/OvLnz59CXCxAQoLr169iza9/OvTt2AQIAiP8fT768+fPo06svL0BAgPfw48ufT7++/fvyBQgAwL+/f4AABA4kWNDgQYQJCwoQEMDhQ4gRJU6kWNFiRAECAGzk2NHjR5AhRY70KEBAAJQpVa5k2dLlS5grBQgAUNPmTZw5de7k2ROnAAEBhA4lWtToUaRJlRYVIADAU6hRpU6lWtXqVakCBATg2tXrV7BhxY4l+1WAAABp1a5l29btW7hx2QoQEMDuXbx59e7l29dvXgECAAwmXNjwYcSJFS82LEBAAMiRJU+mXNnyZcyTBQgA0NnzZ9ChRY8mXRq0AAEBVK9m3dr1a9ixZbcWIADAbdy5de/m3dv3b90CBAQgXtz/+HHkyZUvZ35cgAAA0aVPp17d+nXs2akLEBDA+3fw4cWPJ1/efHgBAgCsZ9/e/Xv48eXPdy9AQAD8+fXv59/fP8AAAgcSLGhwoAABABYybOjwIcSIEic6FCAgAMaMGjdy7OjxI8iNAgQAKGnyJMqUKleybIlSgIAAMmfSrGnzJs6cOmsKEADgJ9CgQocSLWr0qFABAgIwber0KdSoUqdSfSpAAICsWrdy7er1K9iwXAUICGD2LNq0ateybes2rQABAObSrWv3Lt68evfaFSAgAODAggcTLmz4MOLBAgQAaOz4MeTIkidTrgxZgIAAmjdz7uz5M+jQojsLEADgNOrU/6pXs27t+rVqAQIC0K5t+zbu3Lp3874tQACA4MKHEy9u/Djy5MQFCAjg/Dn06NKnU69uPboAAQC2c+/u/Tv48OLHexcgIAD69OrXs2/v/j389QIEAKhv/z7+/Pr38++PH6AAAQEIFjR4EGFChQsZHhQgAEBEiRMpVrR4EWNGigIEBPD4EWRIkSNJljQZUoAAACtZtnT5EmZMmTNdChAQAGdOnTt59vT5E+hOAQIAFDV6FGlSpUuZNkUqQEAAqVOpVrV6FWtWrVUFCADwFWxYsWPJljV7VqwAAQHYtnX7Fm5cuXPpvhUgAEBevXv59vX7F3BgvgIEBDB8GHFixYsZN/92nFiAAACTKVe2fBlzZs2bLQsQEAB0aNGjSZc2fRr1aAECALR2/Rp2bNmzadeGLUBAAN27eff2/Rt4cOG9BQgAcBx5cuXLmTd3/ly5AAEBqFe3fh17du3buV8XIABAePHjyZc3fx59evICBARw/x5+fPnz6de3H1+AAAD7+ff3DxCAwIEECxo8iDChAAEBGjp8CDGixIkUK0IUIACAxo0cO3r8CDKkyI4CBAQ4iTKlypUsW7p8qVKAAAA0a9q8iTOnzp08bwoQECCo0KFEixo9ijQpUQECADh9CjWq1KlUq1qNKkBAgK1cu3r9Cjas2LFeBQgAgDat2rVs27p9C3f/rQABAeravYs3r969fPviFSAAgODBhAsbPow4seLCAgQEeAw5suTJlCtbvixZgAAAnDt7/gw6tOjRpD8LEBAgterVrFu7fg07NmsBAgDYvo07t+7dvHv7zi1AQIDhxIsbP448ufLlxgUIAAA9uvTp1Ktbv459ugABAbp7/w4+vPjx5MuDFyAAgPr17Nu7fw8/vvz2AgQEuI8/v/79/Pv7BxhA4ECCBQUIAJBQ4UKGDR0+hBiRoQABASxexJhR40aOHT1mFCAAwEiSJU2eRJlS5UqTAgQEgBlT5kyaNW3exDlTgAAAPX3+BBpU6FCiRYEKEBBA6VKmTZ0+hRpValMB/wIAXMWaVetWrl29ftUqQEAAsmXNnkWbVu1atmcFCAAQV+5cunXt3sWbl64AAQH8/gUcWPBgwoUNBxYgAMBixo0dP4YcWfJkxwIEBMCcWfNmzp09fwa9WYAAAKVNn0adWvVq1q1RCxAQQPZs2rVt38adW3dtAQIA/AYeXPhw4sWNHxcuQEAA5s2dP4ceXfp06s8FCACQXft27t29fwcfnrsAAQHMn0efXv169u3dpxcgAMB8+vXt38efX/9++wIEAAwgcCDBggYPIkyosKAAAQAeQowocSLFihYvShQgIADHjh4/ggwpciTJjwIEAEipciXLli5fwozJUoCAADZv4hzMqXMnz54+cwoIKnQo0aJGjyJNqnQp06ZOiQYEADs=">
```

**Comment by liZe** [comment]
> Maybe it was because we used href rather than xlink:href?

Yes, you have to use `xlink:href` (that's what the spec tells).

> In addition, I had to make a change to get non-blurry images

I've added the support of [`image-rendering`](https://www.w3.org/TR/SVG11/painting.html#ImageRenderingProperty), you can now use `<image image-rendering="optimizeSpeed"…` to remove bilinear resampling and make images look less blurry.

**Comment by dsblank** [comment]
Thank you for adding the rendering option; I'll try that out when I change the href to xlink:href.

It would be nice that the code here would give an error (or warning) on "href" and suggest using "xlink:href". It just crashes otherwise with no indication of what the problem is.

**Comment by liZe** [comment]
> Thank you for adding the rendering option; I'll try that out when I change the href to xlink:href.

Cool, I hope it'll help.

> It would be nice that the code here would give an error (or warning) on "href" and suggest using "xlink:href". It just crashes otherwise with no indication of what the problem is.

[CairoSVG's philosophy](http://cairosvg.org/documentation/#philosophy) is to be a garbage-in-garbage-out software. There's no error handling when it's not needed. It would need an incredible amount of code to handle errors as it's defined in the spec, and even more to add smart warnings like this one!

**Pull request closed without merging**
