### PR TITLE
Fix #189.

### LINKED ISSUE #189: The linear gradients of svg to pdf is invalid
Hi,
I'm using cairoSVG 2.1.3 on Windows 7 64 bits with Python 3.6.3 64 bits,
cairosvg.svg2pdf() to convert svg to pdf,but is invalid.

svg content:
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" height="881.0px" width="1569.0px" xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)">
    <use height="881.0" transform="matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)" width="1569.0" xlink:href="#shape2"/>
  </g>
  <defs>
    <g id="shape2" transform="matrix(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)">
      <path d="M0.0 0.0 L1569.0 0.0 1569.0 881.0 0.0 881.0 0.0 0.0" fill="url(#gradient0)" fill-rule="evenodd" stroke="none"/>
    </g>
    <linearGradient gradientTransform="matrix(0.0, 0.54, -0.54, 0.0, 784.2, 440.45)" gradientUnits="userSpaceOnUse" id="gradient0" spreadMethod="pad" x1="-819.2" x2="819.2">
      <stop offset="0.0" stop-color="#7573c0"/>
      <stop offset="0.4980392156862745" stop-color="#547fc4"/>
      <stop offset="1.0" stop-color="#328ac8"/>
    </linearGradient>
  </defs>
</svg>
```

### PR DESCRIPTION
**Pull request by juwen**
lineargradients normal display.

### CODE REVIEW

**Comment by liZe** [comment]
Thanks a lot for this pull request!

Your solution in `surface.py` is a smart way to fix your bug (and #161 by the way), I don't know why it wasn't done this way before. Great ideas look so easy once you find them! It would be even better to parse defs when the surface is initialized, it would avoid checking `node.tag` each time `draw` is called, and calling `parse_all_defs` twice when `svg` tags are nested. We can also look for `defs` tags with `ElementTree` instead of parsing the whole tree.

I suppose that the change in `url.py` means that you have a problem on Windows. The real bug is actually in `normalize_url`: we want to keep the URL as-is when it's starting with a `#`.

I can merge the PR right now and fix the little things above later, or I can let you fix them, as you wish!

**Comment by liZe** [comment]
I've kept the first part of the commit, feel free to come back and discuss the second part!

**Comment by aziesemer** [comment]
This change to surface.py broke my svgs. Here is an example:
[floor.svg.txt](https://github.com/Kozea/CairoSVG/files/2550070/floor.svg.txt)
screen shot 2018-11-05 at 1 35 11 pm
screen shot 2018-11-05 at 1 35 06 pm

**Comment by liZe** [comment]
> This change to surface.py broke my SVGs

Could you please open a new issue about your problem, with a link to this issue?

**Pull request closed without merging**
