### PR TITLE
Fix for PDF texts not being selectable

### PR DESCRIPTION
**Pull request by aziesemer**
Decreases PDF file size and allows text selection/copy by rendering the texts as text, instead of paths.

Fixes issue #212.

### CODE REVIEW

**Comment by liZe** [comment]
Hello,

Thanks a lot for your pull request! Using `show_text` is a good idea and would be really useful. But unfortunately, it at least breaks colored text (and probably a couple of other things).

I'll try to see if there's a quick fix for that (you can too!). It's long to carefully check the output from the tests, as many of the failing tests are only failing for hinting reasons, but it's important not to introduce regressions (for the record: it reminds me #80).

**Comment by aziesemer** [comment]
I was not able to appropriately set the test environment here. If you are doing it manually, there are a few tools to compare images that can help:
https://askubuntu.com/questions/209517/does-diff-exist-for-images

**Comment by liZe** [comment]
> I was not able to appropriately set the test environment here.

These two lines should be enough:
```
git submodule update --init
./setup.py test
```

> If you are doing it manually, there are a few tools to compare images that can help

Thank you!

> it at least breaks colored text (and probably a couple of other things).

I suppose that it will also break scales, translations, opacity, filters, and everything that generally transforms the drawing.

**Comment by aziesemer** [comment]
So I compared each one of the test cases that failed. The only issue that I noticed was with the fill and stroke color, everything else was fine (skew, rotation,...). Actually very small letters are slightly misalignment (maybe half a pixel) and the lowercase letters seems slightly taller than it should be.

I'm attaching a zip file with a compilation of the test cases that actually failed, excluding the others that just failed because of small pixel differences.

[CairoSVGFailed.zip](https://github.com/Kozea/CairoSVG/files/2543765/CairoSVGFailed.zip)

**Comment by aziesemer** [comment]
I found a solution that works for all test cases, except "masking-path-04-b.svg". It seems that cairo requires the shape to properly create a mask using the text. Everything else is fine: fill color, stroke, skew,... The only thing that I noticed is that, for PNGs, the current implementation produces texts with small font size with slightly better quality.

On the other hand, we can keep the current implementation for all raster formats, since it doesn't make any difference anyway. But for PDFs only, we can use a flag that will enable this "simplified PDF" with selectable text and smaller file size. Comparing old and new PDFs, the only difference I could notice was with the same "masking-path-04-b.svg".

**Comment by aziesemer** [comment]
So a finally made pushed the changes. There is a new flag called draw_text_as_text that when enabled, changes the draw function to draw text as text instead of as paths, otherwise fallback to the previous implementation (default behaviour).
When enabled, however, it produces smaller PDFs with selectable text but may fail when clipping using the text (example: "masking-path-04-b.svg").

**Comment by liZe** [comment]
Thanks a lot!

> it seems that this PR is working for all test cases and maybe there is no need for the --text-as-text flag

You're right, I'll remove it.

**Comment by liZe** [comment]
Hmmmmm… Some tests are broken (at least tspan02, tspan-dx-dy, toap04).

**Comment by aziesemer** [comment]
@liZe  Some remarks:
- Comment "May not support some path clipping operations." can be removed.
- This line should be preserved:  "alignment_baseline == 'hanging' or

**Comment by aziesemer** [comment]
I created a new PR #222 that fixes tspan. It was caused by the shallow copy of the save_cursor list. Deep copying solved it.

**Pull request merged**
