### PR TITLE
Fix tspan with --text-as-text

### PR DESCRIPTION
**Pull request by aziesemer**

### CODE REVIEW

**Comment by aziesemer** [comment]
@liZe Please accept this pull request. TSPAN support was broken because I was saving the cursor position using shallow copy instead of deep copy. So it was not working at all when restoring.

**Comment by liZe** [comment]
I'm trying to make tests pass again, it's long and painful :cry:.

**Comment by aziesemer** [comment]
> I'm trying to make tests pass again, it's long and painful 😢.

You have my thoughts and prayers! 💪

**Comment by liZe** [comment]
> You have my thoughts and prayers!

Thank you :smile:.

Here are the broken tests (text on paths):
- text-align-04-b.svg
- text-path-01-b.svg
- text-path-02-b.svg
- toap01.svg
- toap02.svg
- toap03.svg
- toap04.svg

As I don't want to manually check the whole test suite again and again, I'll commit a change that make tests pass, even if we know that they don't pass. The goal is to fix this, and our change should make the non-regression tests fail **only for these files**.

**Comment by liZe** [comment]
> The goal is to fix this, and our change should make the non-regression tests fail **only for these files**.

c9abc1b breaks exactly these 7 tests, and manual checks tell me that it's … fixed! We're back to normal.

Note for later: don't accept pull requests with failing tests :wink:.

**Pull request merged**
