### PR TITLE
Update parser.py

### PR DESCRIPTION
**Pull request by kelvin13**
make gradients and markers work

### CODE REVIEW

**Comment by liZe** [comment]
Thank you for your pull request.

Your commit broke a test (you can find the details in Travis' page), because case-sensitivity is stupidly complicated in SVG :(. I'd be really happy to have a real solution for this bug, so if you could find the time and courage to read the specification and provide a better patch, I'll merge it and you'll be one of my heroes :).

**Comment by liZe** [comment]
@kelvin13 Are you interested in fixing this bug, or can I close this pull request?

**Comment by kelvin13** [comment]
You can close this pull request. I feel that this change is still an improvement over the previous state, because a renderer that occasionally produces unstandard output is preferable to one that simply does not work at all. 

My understanding of svg syntax is probably much worse than yours so i don’t see a standards-perfect solution coming from me any time soon

**Comment by liZe** [comment]
Fixed by #100.

**Pull request closed without merging**
