### PR TITLE
Add output size parameters

### PR DESCRIPTION
**Pull request by hugodelahousse**
I added output_width and output_height parameters to the converter. This is helpful when you want to resize an svg without knowing the original size.
The scale is computed from one parameter if only one dimension is specified, otherwise the width and height fields of the surface are directly set to the desired output size.

### CODE REVIEW

**Comment by aziesemer** [comment]
Hi @liZe, 
I'm using cairosvg in a project and I need to save PNGs in a specific resolution. This pull request seems to be exactly why I need. Is there any reason for it not being merged yet, like bugs?

**Comment by liZe** [comment]
> Is there any reason for it not being merged yet, like bugs?

To be honest, I'm not a huge fan of this feature for various reasons I've already discussed a million times. But I must admit people find it useful, so let's merge it.

**Comment by liZe** [comment]
I'll check that everything works fine, update the CLI and the documentation (what does happen when both scale and output size are given?), and release a version during the next week.

**Comment by aziesemer** [comment]
I was trying to convince my coleagues that dpi was enought but they really wanted to be able to set the resolution.

**Pull request merged**
